### ISSUE TITLE
Uruchamianie testów na Windowsie

### ISSUE THREAD

**Issue by przeprogramowani** [przeprogramowani/advent-of-frontend#17]
Cześć,

Dostaliśmy informację, że uruchamianie testów na Windowsie wg wzorca YYYY-MM-DD nie działa, a w zamian są uruchamiane wszystkie testy.

Nie jest to optymalny experience, więc chcielibyśmy poprawić nasze skrypty tak, aby były prawdziwie cross-platform.

Otwieram wątek na wasze propozycje, jeśli ktoś jest chętny to czekamy na PR.

//Przemek

**Comment by kumiega** [comment]
Rozkminiałem ten temat i wydaje mi się, że bez osobnego skryptu nie da się tego rozwiązać. Obecnie ten sposób, który jest użyty w package.json działa jedynie na WSL-u, bo tam jest powłoka linuxowa. Ani Git for Windows ani PowerShell nie obsłużą tego prawidłowo.

**Comment by mystertaran** [comment]
@kumiega prawdopodobnie pomyśleliśmy podobnie. Próbowałem na różne sposoby to obejść lub poprawić, ostatecznie stworzyłem skrypt i wywołuje testy za pomocą node, ale wykorzystując do tego bibliotekę jest. 

W PR zaproponowałem to rozwiązanie.

**Comment by przeprogramowani** [comment]
@mystertaran PR zmergowany 🎁
